<Project>
    <PropertyGroup Label="Package">
        <Company>Fontys Greentech</Company>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>false</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>
</Project>

